<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Rental.Application\Rental.Application.csproj" />
    <ProjectReference Include="..\Rental.Domain\Rental.Domain.csproj" />
    <ProjectReference Include="..\Rental.Infra.Data\Rental.Infra.Data.csproj" />
  </ItemGroup>

</Project>
